theme: jekyll-theme-cayman

include:
  - _colon.png
  - _comma.png
  - _div.png
  - _equal.png
  - _exclamation.png
  - _minus.png
  - _mult.png
  - _plus.png
  - _point.png
  - _question.png
  - _semicolon.png
  - _space.png
  - _open_square_bracket.png
  - _close_square_bracket.png
  - _open_round_bracket.png
  - _close_round_bracket.png
  - _open_curly_bracket.png
  - _close_curly_bracket.png
